### ISSUE TITLE
ImportError: No module named 'pygeoip' 

### ISSUE THREAD

**Issue by vherasme** [appliedsec/pygeoip#65]
Hi,

I am using python 3.4.1 and I am trying to load this module in order to use it with pandas. I am receiving the follwoing error:

ImportError                               Traceback (most recent call last)
<ipython-input-24-fc3915e287f0> in <module>()

----> 1 import pygeoip
        2 gi = pygeoip.GeoIP('./GeoLiteCity.dat', pygeoip.MEMORY_CACHE)

ImportError: No module named 'pygeoip'

**Comment by tiwilliam** [comment]
I'm not too familiar with IPython and you might already have solved this.

**Comment by Wangjiye** [comment]
You will need to install pygeoip, and you'll have to do the command: pip install pygeoip

**Comment by cell13** [comment]
I meet the same problem after i installed the pygeoip using the command "pip install pygeoip".
the old code:
import pygeoip gip = pygeopip.GeoIP('GeoLiteCity.dat') rec = gip.record_by_addr(raw_input("input the IP of you want:")) print rec
ee, there is something wrong, the error message is "NameError: name 'pygeopip' is not defined". You know, there is another way to use the method of module. So let's have a try the below code.
the new code:
from pygeoip import * gip = GeoIP('GeoLiteCity.dat') rec = gip.record_by_addr(raw_input("input the IP of you want:")) print rec
YES! Here is no error again. A good day, thanks.

**Comment by richarson** [comment]
Notice this in your old code (extra 'p'):

gip = pygeo**p**ip.GeoIP('GeoLiteCity.dat')

**Comment by cell13** [comment]
hha, my falut. So careless. Both of method are ok.
