### ISSUE TITLE
"pygeoip __init__.py _gethostbyname" Error.

### ISSUE THREAD

**Issue by BhaiX** [appliedsec/pygeoip#76]
Hello,

I hope you guys know there is a python IRC bot Willie, To make his .ip command work we need pygeoip, I've installed it and its working but when I type.

<@Bhai> .ip Bhai
<Ji> gaierror: [Errno -2] Name or service not known (file "/usr/local/lib/python2.7/dist-packages/pygeoip/__init__.py", line 394, in _gethostbyname)

This Error, Any way to fix it?

**Comment by tiwilliam** [comment]
Since `Bhai` isn't a valid hostname our underlying socket library will complain. `pygeoip` won't catch and re-raise this error so if you want a nicer presentetion you'll have to catch this in `Willie`.
